### ISSUE TITLE
Output argument "st_letter" not assigned a value in the execution with "f_GetLetterSize" function

### ISSUE THREAD

**Issue by rahilvaknalli** [mnavarretem/RIPPLELAB#1]
Hi! I am attempting to run RippleLab on my laptop and noticed that I am getting an error on Line 65 of the code. Could you please let me know if there are any fixes? Thanks!

**Comment by DFBRipple** [comment]
Me too. Can you help us?

**Comment by mnavarretem** [comment]
Usually, this error is displayed when the code can't access the
f_GetLetterSize function which is located in
.\RIPPLELAB\Functions\Miscellaneous. For avoiding this issue, please make
sure RIPPLELAB is on path including all RIPPLELAB subfolders:
addpath(genpath('your-path\RIPPLELAB'))
Miguel
